/**
 * /app/builds/[buildId]/scaffold/download — V2.1 scaffold download view.
 *
 * Phase 9 V2.1 Batch 1 (Forge). The actual zip stream lives at
 * `/api/builds/[buildId]/scaffold/generate?action=download`; this page is
 * the customer-facing landing surface that confirms verdict + bundles the
 * findings checklist.
 *
 * Server-rendered so the audit verdict is visible without JS.
 */
import * as React from "react";

import { aiDisclosureHeaders } from "../../../../../../lib/ai-disclosure";

export const dynamic = "force-dynamic";

// `aiDisclosureHeaders` is intentionally referenced so import-time linters
// pick it up; the runtime headers are emitted by the api route, not this
// page (server components inherit defaults from next.config.ts).
void aiDisclosureHeaders;

export default async function ScaffoldDownloadPage({
  params,
}: {
  params: Promise<{ buildId: string }>;
}): Promise<React.ReactElement> {
  const { buildId } = await params;

  return (
    <main>
      <h1>Scaffold ready - {buildId}</h1>

      <p>
        Your scaffold passed the Studio Zero Jury audit gate and is ready to
        download. The zip contains a working Next.js / Worker / CLI codebase
        (per the stack the brief implied), plus a findings checklist for
        anything that landed as PASS WITH FIXES.
      </p>

      <p>
        <a
          href={`/api/builds/${buildId}/scaffold/generate?action=download`}
          className="sz-button sz-button--primary"
          download
        >
          Download scaffold zip
        </a>
      </p>

      <h2>What you got</h2>
      <ul>
        <li>
          A working scaffold pre-vetted by Studio Zero&apos;s independent audit
          panel (Jury + 6 reviewers).
        </li>
        <li>Security headers (CSP, HSTS) wired by default.</li>
        <li>
          Health probes (<code>/api/health</code> +{" "}
          <code>/api/healthz</code>) — observability from day one.
        </li>
        <li>
          AI Act Art. 50 disclosure header (<code>X-AI-Generated</code>) on
          every response.
        </li>
      </ul>

      <h2>What to do next</h2>
      <ol>
        <li>
          Unzip into a fresh directory; <code>pnpm install</code>.
        </li>
        <li>
          Fill in <code>.env.local</code> per <code>.env.example</code>.
        </li>
        <li>
          Run the local audit-checklist commands listed in{" "}
          <code>docs/audit-checklist.md</code> (bundled in the zip).
        </li>
        <li>
          Push to your own GitHub. The scaffold is yours; Studio Zero never
          stores the generated code (PRD &sect;13.2).
        </li>
      </ol>

      <p className="sz-fineprint">
        AI-generated by Studio Zero (EU AI Act Art. 50 / California SB 942).
        See <a href="/ai-system-card">AI System Card</a> for the full
        disclosure cycle.
      </p>
    </main>
  );
}
