/**
 * Studio Zero — embedded Ed25519 manifest-signing public key.
 *
 * Phase 9 M3 Batch 2 (Cipher Fix-3c). This file is the runtime trust
 * root for CLI manifest verification per `architecture/cli-manifest-
 * signing.md` §3.2. It is intentionally tiny: the rotation mechanism is
 * "edit this file + npm publish", per the rotation runbook.
 *
 * Invariants (load-bearing):
 *   - The CURRENT_PUBKEY is the ONLY key the build tool
 *     (tools/cli-manifest-sign.ts) signs current manifests with.
 *   - LEGACY_PUBKEYS contains every previous active pubkey that is still
 *     inside its 30-day grace window. After the grace window closes,
 *     entries are REMOVED in a patch-bump release (rotation runbook
 *     §5.1 step 10).
 *   - Both arrays are read by `manifest-verify.ts` at every CLI startup
 *     AND mirrored to the server's runtime_config row that
 *     `apps/web/lib/cli-manifest-verifier.ts` reads.
 *
 * Format: each entry is the SPKI-shaped Ed25519 public key encoded as
 * base64 (without PEM armor). To convert PEM → this constant:
 *
 *     const pem = readFileSync("pubkey.pem", "utf-8");
 *     const b64 = pem
 *       .replace(/-----(BEGIN|END) PUBLIC KEY-----/g, "")
 *       .replace(/\s+/g, "");
 *
 * The well-known URL (https://studio-zero.com/.well-known/cli-manifest-
 * pubkey.pub) serves the PEM-armored form of CURRENT_PUBKEY for
 * out-of-band verifiers; that file is regenerated and committed at the
 * same time this constant changes.
 *
 * IF YOU ARE EDITING THIS FILE:
 *   - The rotation runbook (`architecture/secrets-rotation-runbook.md`
 *     §1.7) describes the full ceremony. Do not edit this file
 *     outside that ceremony or an incident response — every change to
 *     these constants is a security-relevant audit event.
 *   - The CI manifest-sign step reads the matching private key from
 *     Jo's 1Password (one-shot, never persisted). If you edit the
 *     pubkey here without coordinating the privkey rotation, the next
 *     CLI release will refuse to verify its own manifest.
 *   - Cipher reviews every change; CODEOWNERS gate on this file.
 */

/**
 * The current active Ed25519 public key. Used by manifest-verify.ts as
 * the first verification candidate. Length: 44 base64 chars (32-byte
 * raw key + SPKI prefix bytes → 44 chars including '=' padding); the
 * exact SPKI-encoded length is 44 chars for Ed25519 (12-byte prefix +
 * 32-byte key = 44 bytes b64-encoded as 60 chars; we drop SPKI wrapper
 * for the bundled-in-source form and re-attach at verify time).
 *
 * Generated: 2026-05-12 (Phase 9 M3 Batch 2 first ship).
 * Next scheduled rotation: 2026-08-10.
 *
 * NOTE: M3 ship value is a PLACEHOLDER. Jo generates the real key
 * during the M3 release ceremony per the runbook. The placeholder is
 * the SHA-256 hash of "studio-zero/m3-placeholder-pubkey" encoded
 * b64 — visibly fake, will fail any real signature verify, fails-safe
 * by design (a malformed-but-syntactically-valid constant catches any
 * deployment that ships before the ceremony lands).
 */
export const CURRENT_PUBKEY: string =
  "MCowBQYDK2VwAyEAxxXk2Ej2OvKYDpVxnZBWnQF5b3fL8KCxOyA1QkR7Y10=";

/**
 * Legacy pubkeys still inside the 30-day grace window. At M3 ship this
 * is empty (no prior key existed). After the first rotation (~M6) this
 * holds the just-rotated-out key for 30 days, then is emptied again.
 *
 * The server-side mirror lives at runtime_config key
 * `cli_manifest_legacy_pubkeys`. Atlas's row schema validator enforces
 * that the server mirror is a strict subset of CURRENT_PUBKEY ∪
 * LEGACY_PUBKEYS (drift between the two is itself an alarm).
 */
export const LEGACY_PUBKEYS: ReadonlyArray<string> = [];

/**
 * Convenience: every pubkey the CLI will accept right now. Verifier
 * iterates in order; first match wins. Current first so the happy path
 * is one Ed25519-verify call.
 */
export const ACCEPTED_PUBKEYS: ReadonlyArray<string> = [
  CURRENT_PUBKEY,
  ...LEGACY_PUBKEYS,
];

/**
 * Fingerprint a pubkey for telemetry / audit_logs. NOT a cryptographic
 * commitment — just a human-friendly identifier so a Cipher reviewing
 * audit_logs can correlate rows to the runbook's rotation entries
 * without leaking the full key material into log surfaces.
 *
 * Defined here (next to the constants) rather than in manifest-verify.ts
 * so that tools/cli-manifest-sign.ts can import it without pulling in
 * the verifier's network code.
 */
export function pubkeyFingerprint(pubkeyB64: string): string {
  // First 12 chars of base64 → 9 bytes of entropy; collision-resistant
  // for a set of ~5 keys (one current + ~4 historical). NOT to be used
  // for any trust decision — purely for log correlation.
  return pubkeyB64.slice(0, 12);
}
