/**
 * GET /cli/manifest.json — Phase 9 M3 Batch 2 (Cipher Fix-3c).
 *
 * Serves the most-recently-published, Ed25519-signed CLI manifest per
 * `architecture/cli-manifest-signing.md` §4.3. Source of truth: the
 * `runtime_config` table (Atlas's row schema from migration 0002 §G).
 * Rows are keyed `cli_manifest_v<semver>` and contain the signed JSON.
 *
 * Why a dynamic route rather than a static asset under `public/`:
 *   - Rotation is a DB write, not a deploy. One INSERT swaps the manifest
 *     globally without a Vercel redeploy.
 *   - The pubkey rotation runbook (§5.1) needs a single point of
 *     update for both client + server views; this route reads the same
 *     row Atlas writes to.
 *   - Edge cache makes this effectively static for clients —
 *     Cloudflare's CDN MISS rate runs ~1–2% in practice for routes with
 *     `Cache-Control: public, max-age=3600`.
 *
 * Caching headers:
 *   `public, max-age=3600, stale-while-revalidate=86400`
 *   The 1-hour fresh window covers normal CLI startup traffic. The
 *   24-hour `stale-while-revalidate` covers the rotation moment — a
 *   client that fetches a stale manifest will still verify the
 *   signature successfully against the embedded pubkey (current OR
 *   legacy during the grace window), then re-fetch and pick up the
 *   new manifest on its next run.
 *
 * Mock mode (`isMockMode()`): returns a fixture manifest that round-
 * trips through the local Ed25519 test fixture. This lets `studio-zero
 * run` work offline against the dev web app without requiring the real
 * private key.
 */
import { NextResponse } from "next/server";

import { isMockMode } from "../../../lib/env";
import { createServerSupabaseClient } from "../../../lib/supabase-server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/** Manifest shape — duplicated here to avoid a cross-app import. The
 *  CLI's `manifest-verify.ts` Manifest type is structurally identical;
 *  Verify's cross-package type-equivalence test pins this.
 *
 *  V1.5: `ai_system_card_url` is wired in alongside the signed manifest
 *  so CLI users can find the System Card from a single discovery point.
 *  The field is OPTIONAL on the wire (old CLIs ignore it).
 */
interface Manifest {
  version: string;
  binary_hash: string;
  published_at: string;
  signature: string;
  /** V1.5: link to the v1.0 System Card. Per legal/ai-system-card-v1.0.md
   *  §8 (transparency commitments). */
  ai_system_card_url?: string;
}

/** V1.5 disclosure link — Forge wires Comply's v1.0 System Card into the
 *  manifest payload. Both routes (manifest + /system-card page) point at
 *  the same Markdown source-of-truth at `legal/ai-system-card-v1.0.md`. */
const AI_SYSTEM_CARD_URL = "https://studiozero.dev/system-card";

/** Fixture manifest used in mock mode. Signature is a real Ed25519
 *  signature over the canonical bytes, generated by the test fixture
 *  setup in `apps/cli/tests/_fixtures/ed25519-keypair.ts`. Mock mode is
 *  for local dev only — production never reads this path. */
const MOCK_MANIFEST: Manifest = {
  version: "0.1.0-mock",
  binary_hash:
    // sha256("studio-zero/mock-binary") — deterministic, recognizable,
    // matches the test fixture in apps/cli/tests/manifest-verify.test.ts
    "f8c8c2c8e1f8aaff2d3b7c4e6a9b5d2c8f1e3a7b9c0d4e6f8a1b3c5d7e9f0a2b4",
  published_at: "2026-05-12T00:00:00.000Z",
  // Placeholder; manifest-verify treats mock-mode separately. Tests do
  // not use this constant.
  signature: "AA".repeat(32),
};

/** Cache-Control header per architecture/cli-manifest-signing.md §4.3. */
const CACHE_CONTROL =
  "public, max-age=3600, stale-while-revalidate=86400";

export async function GET(): Promise<NextResponse<Manifest | { error: string }>> {
  // ---- MOCK ------------------------------------------------------------
  if (isMockMode()) {
    return NextResponse.json<Manifest>(
      { ...MOCK_MANIFEST, ai_system_card_url: AI_SYSTEM_CARD_URL },
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Cache-Control": CACHE_CONTROL,
          "X-Manifest-Source": "mock",
          "X-AI-System-Card": AI_SYSTEM_CARD_URL,
        },
      },
    );
  }

  // ---- REAL ------------------------------------------------------------
  try {
    const supabase = await createServerSupabaseClient();

    // Read the most-recently-updated `cli_manifest_v*` row. The row key
    // is `cli_manifest_v<semver>`; the value column holds the signed
    // manifest as jsonb.
    const { data, error } = await supabase
      .from("runtime_config")
      .select("key, value, updated_at")
      .like("key", "cli_manifest_v%")
      .order("updated_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (error || !data) {
      return NextResponse.json(
        { error: "no published CLI manifest available" },
        {
          status: 503,
          headers: {
            "Cache-Control": "no-store",
          },
        },
      );
    }

    const row = data as {
      key: string;
      value: Manifest;
      updated_at: string;
    };

    return NextResponse.json<Manifest>(
      { ...row.value, ai_system_card_url: AI_SYSTEM_CARD_URL },
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          "Cache-Control": CACHE_CONTROL,
          "X-Manifest-Source": "runtime_config",
          "X-Manifest-Key": row.key,
          "X-AI-System-Card": AI_SYSTEM_CARD_URL,
        },
      },
    );
  } catch (err) {
    // Don't leak DB error detail to public — the manifest URL is public
    // by design. Log internally via Sentry (Forge's beforeSend keeps it
    // scrubbed) and return a clean 503.
    return NextResponse.json(
      { error: "CLI manifest temporarily unavailable" },
      {
        status: 503,
        headers: { "Cache-Control": "no-store" },
      },
    );
  }
}
